### ISSUE TITLE
Bayesian Optimization: Timeline?

### ISSUE THREAD

**Issue by jbrea** [theogf/OMGP.jl#2]
Hi Théo

Nice package!

I would like to try it for some Bayesian optimization and saw that you started already (with an almost empty file) in this direction. What are your plans on implementing Bayesian optimization methods? Does it have high priority or low?

Cheers
Johanni

**Comment by theogf** [comment]
Hello,

The idea for the Bayesian Optimization file was actually more in the direction of the GP hyperparameter optimization since I was not satisfied with the current Gradient Ascent technique (based on Adam).
But it should be easy to write your own script using the Regression or SparseRegression model.

**Comment by jbrea** [comment]
I see. Thanks.
